# Generated by Django 2.0 on 2017-12-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=20)),
                ('fileType', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileType', models.CharField(max_length=4)),
                ('caption', models.CharField(max_length=2000)),
                ('iamgeNmae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.image')),
            ],
        ),
    ]
