# Generated by Django 2.0 on 2017-12-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageName',
            field=models.FileField(upload_to=''),
        ),
    ]
